<?php

use Illuminate\Http\Request;

define('LARAVEL_START', microtime(true));

$deployRoot = '/home/html/kbelstisokoli.cz/public_html/secret/deploy';
$releasesRoot = $deployRoot.'/releases/';
$appBase = realpath($deployRoot.'/current');

if ($appBase === false || ! str_starts_with($appBase.'/', $releasesRoot)) {
    http_response_code(503);
    header('Content-Type: text/plain; charset=UTF-8');
    echo 'Application release is unavailable.';
    exit;
}

$releaseId = basename($appBase);
header('X-App-Release: '.$releaseId);
define('LARAVEL_RELEASE_ID', $releaseId);
define('LARAVEL_RELEASE_PUBLIC_PATH', $appBase.'/public');

if (file_exists($maintenance = $appBase.'/storage/framework/maintenance.php')) {
    require $maintenance;
}

// Fast cache is namespaced by release. A deployment therefore never serves HTML
// generated by an older version while still avoiding a global Redis flush.
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'GET'
    && strtolower($_SERVER['HTTP_HOST'] ?? '') === 'kbelstisokoli.cz'
    && ! isset($_COOKIE['kbelsti-sokoli-session'])
    && ! isset($_SERVER['HTTP_X_PRIME_CACHE'])
    && ! isset($_GET['screenshot_user_id'])
) {
    $uriPath = ltrim(explode('?', $_SERVER['REQUEST_URI'] ?? '/')[0], '/');
    $uriPath = $uriPath === '' ? '/' : $uriPath;

    if (! str_starts_with($uriPath, 'admin') && ! str_starts_with($uriPath, 'clenska-sekce')) {
        $queryParams = $_GET;
        ksort($queryParams);

        $redis = new Redis;
        if (@$redis->connect('c-redis', 6379, 0.05)) {
            $redis->select(1);
            $prefix = 'kbelsti-sokoli-database-kbelsti-sokoli-cache-full_page_'.$releaseId.'_';

            foreach (['cs', 'en'] as $locale) {
                $key = $prefix.md5($uriPath.'_'.serialize($queryParams).'_'.$locale);
                $cached = $redis->get($key);

                if ($cached) {
                    $data = unserialize($cached, ['allowed_classes' => false]);
                    if (is_array($data) && isset($data['content'])) {
                        header('Content-Type: '.($data['type'] ?? 'text/html; charset=UTF-8'));
                        header('X-Page-Cache: fast-hit');
                        header('X-Fast-Cache-Locale: '.$locale);
                        header('Cache-Control: public, max-age=300, stale-while-revalidate=600');
                        echo $data['content'];
                        exit;
                    }
                }
            }
        }
    }
}

require $appBase.'/vendor/autoload.php';

(require_once $appBase.'/bootstrap/app.php')
    ->handleRequest(Request::capture());
