@extends('emails.layouts.base')
@section('title', __('attendance_mail.reminder.heading'))
@section('preheader', __('attendance_mail.reminder.preheader', ['team' => $teamNames]))
@section('content')
<table width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><td style="padding:0 0 30px"><table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="overflow:hidden;border-radius:14px;background:#0B1F3A;background-image:linear-gradient(135deg,#0B1F3A 0%,#172F52 100%)"><tr><td style="padding:32px 34px 30px"><table width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><td><span style="display:inline-block;padding:6px 11px;border-radius:99px;background:#E11D48;color:#FFF;font-size:10px;font-weight:bold;letter-spacing:1.5px;text-transform:uppercase">{{ __('attendance_mail.reminder.badge') }}</span></td><td align="right" style="color:#FFF;font-size:12px;font-weight:bold;letter-spacing:.8px">{{ $teamNames }}</td></tr></table><h1 style="margin:25px 0 11px;color:#FFF;font-size:29px;line-height:1.16;letter-spacing:-.4px">{{ __('attendance_mail.reminder.heading') }}</h1><p style="margin:0;color:#CBD5E1;font-size:15px;line-height:1.6">{{ __('attendance_mail.reminder.intro', ['name' => $user->first_name ?: $user->name]) }}</p></td></tr><tr><td height="5" style="height:5px;background:#E11D48;font-size:0;line-height:0">&nbsp;</td></tr></table></td></tr></table>
<table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="margin-bottom:25px;border:1px solid #E2E8F0;border-radius:12px;background:#FFF"><tr><td width="74" valign="top" style="padding:23px 0 23px 23px"><table width="52" height="52" cellpadding="0" cellspacing="0" role="presentation" style="width:52px;height:52px;border-radius:13px;background:#FFF1F2"><tr><td align="center" valign="middle" style="color:#E11D48;font-size:22px;font-weight:bold">KS</td></tr></table></td><td style="padding:23px 23px 23px 16px"><div style="margin-bottom:9px;color:#0B1F3A;font-size:21px;line-height:1.25;font-weight:bold">{{ $eventName }}</div><table cellpadding="0" cellspacing="0" role="presentation"><tr><td style="padding:2px 9px 2px 0;color:#E11D48;font-weight:bold">●</td><td style="padding:2px 0;color:#475569;font-size:14px">{{ $startsAt->translatedFormat('l j. n. Y · H:i') }}</td></tr>@if($event->location)<tr><td style="padding:2px 9px 2px 0;color:#0B1F3A;font-weight:bold">◆</td><td style="padding:2px 0;color:#475569;font-size:14px">{{ $event->location }}</td></tr>@endif</table></td></tr></table>
<p style="margin:0 4px 23px;color:#334155;font-size:15px;line-height:1.7;text-align:center">{{ __('attendance_mail.reminder.motivation') }}</p>
<table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="margin-bottom:16px"><tr><td width="49%" align="center" bgcolor="#15803D" style="border-radius:9px"><a href="{{ $yesUrl }}" style="display:block;padding:16px 8px;color:#FFF;text-decoration:none;font-weight:bold;font-size:17px">✓&nbsp; {{ __('attendance_mail.actions.yes') }}</a></td><td width="2%"></td><td width="49%" align="center" bgcolor="#BE123C" style="border-radius:9px"><a href="{{ $noUrl }}" style="display:block;padding:16px 8px;color:#FFF;text-decoration:none;font-weight:bold;font-size:17px">×&nbsp; {{ __('attendance_mail.actions.no') }}</a></td></tr></table>
<p style="margin:0 0 31px;text-align:center;color:#94A3B8;font-size:11px;line-height:1.5">{{ __('attendance_mail.reminder.secure_note') }}</p><p style="margin:0;text-align:center"><a href="{{ $detailUrl }}" style="color:#0B1F3A;font-size:14px;font-weight:bold;text-decoration:none;border-bottom:1px solid #CBD5E1;padding-bottom:2px">{{ __('attendance_mail.actions.detail') }} →</a></p>
<table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="margin-top:32px;border-top:1px solid #E2E8F0"><tr><td style="padding-top:18px;color:#94A3B8;font-size:11px;line-height:1.55;text-align:center">{{ __('attendance_mail.unsubscribe.text') }} <a href="{{ $unsubscribeUrl }}" style="color:#64748B;text-decoration:underline">{{ __('attendance_mail.unsubscribe.link') }}</a></td></tr></table>
@endsection
