@extends('emails.layouts.base')
@section('title', __('attendance_mail.summary.heading'))
@section('preheader', __('attendance_mail.summary.preheader', ['team' => $teamNames]))
@section('content')
@php($total = collect($groups)->sum(fn($group) => $group->count()))
<table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="overflow:hidden;border-radius:14px;background:#0B1F3A;background-image:linear-gradient(135deg,#0B1F3A 0%,#172F52 100%);margin-bottom:25px"><tr><td style="padding:31px 34px 29px"><table width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><td><span style="display:inline-block;padding:6px 11px;border-radius:99px;background:#E11D48;color:#FFF;font-size:10px;font-weight:bold;letter-spacing:1.5px;text-transform:uppercase">{{ __('attendance_mail.summary.badge') }}</span></td><td align="right" style="color:#FFF;font-size:12px;font-weight:bold">{{ $teamNames }}</td></tr></table><h1 style="margin:23px 0 8px;color:#FFF;font-size:29px;line-height:1.16;letter-spacing:-.4px">{{ __('attendance_mail.summary.heading') }}</h1><div style="color:#CBD5E1;font-size:15px;line-height:1.6">{{ $eventName }}</div><div style="margin-top:8px;color:#94A3B8;font-size:13px">{{ $startsAt->translatedFormat('l j. n. Y · H:i') }}@if($event->location) &nbsp;•&nbsp; {{ $event->location }}@endif</div></td></tr><tr><td height="5" style="height:5px;background:#E11D48;font-size:0;line-height:0">&nbsp;</td></tr></table>
<table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="margin-bottom:25px"><tr>@foreach(['confirmed'=>['#15803D','#F0FDF4'],'declined'=>['#BE123C','#FFF1F2'],'pending'=>['#64748B','#F8FAFC']] as $status=>[$color,$bg])<td width="32%" align="center" style="padding:16px 6px;background:{{ $bg }};border:1px solid #E2E8F0;border-radius:10px"><div style="color:{{ $color }};font-size:25px;font-weight:bold;line-height:1">{{ $groups[$status]->count() }}</div><div style="margin-top:7px;color:#64748B;font-size:10px;font-weight:bold;text-transform:uppercase;letter-spacing:.7px">{{ __('attendance_mail.status.'.$status) }}</div></td>@if(!$loop->last)<td width="2%"></td>@endif @endforeach</tr></table>
<div style="margin:0 0 13px;color:#64748B;font-size:11px;font-weight:bold;text-transform:uppercase;letter-spacing:1.1px">{{ __('attendance_mail.summary.roster_label', ['count'=>$total]) }}</div>
@foreach(['confirmed'=>['#15803D','#F0FDF4','✓'],'declined'=>['#BE123C','#FFF1F2','×'],'maybe'=>['#B45309','#FFFBEB','?'],'pending'=>['#64748B','#F8FAFC','·']] as $status=>[$color,$bg,$icon])<table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="margin-bottom:11px;border:1px solid #E2E8F0;border-radius:10px;background:#FFF"><tr><td width="48" align="center" valign="top" style="padding:15px 0 15px 14px"><span style="display:inline-block;width:27px;height:27px;line-height:27px;border-radius:50%;background:{{ $bg }};color:{{ $color }};font-weight:bold;text-align:center">{{ $icon }}</span></td><td style="padding:14px 15px 14px 8px"><div style="margin-bottom:5px;color:{{ $color }};font-size:12px;font-weight:bold;text-transform:uppercase;letter-spacing:.6px">{{ __('attendance_mail.status.'.$status) }} · {{ $groups[$status]->count() }}</div><div style="color:#1E293B;font-size:14px;line-height:1.55">{{ $groups[$status]->isEmpty() ? '—' : $groups[$status]->pluck('name')->join(', ') }}</div></td></tr></table>@endforeach
<table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="margin-top:27px"><tr><td align="center"><table cellpadding="0" cellspacing="0" role="presentation"><tr><td bgcolor="#E11D48" style="border-radius:8px"><a href="{{ $detailUrl }}" style="display:inline-block;padding:14px 25px;color:#FFF;text-decoration:none;font-weight:bold;font-size:15px">{{ __('attendance_mail.actions.open_roster') }} &nbsp;→</a></td></tr></table></td></tr></table>
<table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="margin-top:31px;border-top:1px solid #E2E8F0"><tr><td style="padding-top:18px;color:#94A3B8;font-size:11px;line-height:1.55;text-align:center">{{ __('attendance_mail.unsubscribe.summary_text') }} <a href="{{ $unsubscribeUrl }}" style="color:#64748B;text-decoration:underline">{{ __('attendance_mail.unsubscribe.link') }}</a></td></tr></table>
@endsection
